apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tlspassthrough-contour
  namespace: default
spec:
  virtualhost:
    fqdn: passthrough.contour.local
    tls:
      passthrough: true
      minimumProtocolVersion: "1.3"
    #tcpproxy:
  tcpproxy: 
    services:
    - name: svc-tlspassthrough
      port: 9234
---
apiVersion: v1
kind: Service
metadata:
  name: svc-tlspassthrough
spec:
  ports:
  - port: 9234
    targetPort: 5678
  selector:
    app: tlspassthrough
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlspassthrough
spec:
  selector:
    matchLabels:
      app: tlspassthrough
  replicas: 2
  template:
    metadata:
      labels:
        app: tlspassthrough
    spec:
      containers:
      - name: tlspassthrough
        image: harbor.corp.tanzu/library/http-echo
        args:
        - "-text=Yep. I did the TLS Decryption at the backend"
        ports:
        - containerPort: 5678

       #image: harbor.corp.tanzu/library/httpsportal
       #env:
       # - name: SERVERNAME
       #   value: "tls.contour.local"
       # - name: EXTRANAMES
       #   value: "tls.contour.local, https://tls.contour.local"
       # ports:
       # - containerPort: 443
