kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-cluster-user-devops1
roleRef:
  kind: ClusterRole
  name: edit                             #Default ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  #name: sso:devops1@vsphere.local            #sso:<username>@<domain>
  name: sso:${TKC_CLUSTER_USER}            #sso:<username>@<domain>
  apiGroup: rbac.authorization.k8s.io
