apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-https
  annotations:
    kubernetes.io/ingress.class: "nsx"
    #kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.allow-http: "false"
    ingress.kubernetes.io/rewrite-target: /
    #ncp/ssl-mode: "passthrough" 
    #ncp/ssl-mode: "reencrypt" 
    ncp/ssl-mode: "offload" 
    
spec:
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: svc-tea
          servicePort: 443
      - path: /coffee
        backend:
          serviceName: svc-coffee
          servicePort: 443
