apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nginx-4lb
  name: my-nginx-4lb
  namespace: default
spec:
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx-4lb
  sessionAffinity: None
  type: LoadBalancer
